[workspace]
members = ["puroro", "puroro-codegen", "sandbox"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Shohei Wada <pc@wada314.jp>"]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/wada314/puroro"

[workspace.dependencies]
# External utility crates
protobuf-core = "0.1"
protoc-plugin-by-closure = { git = "https://github.com/wada314/protoc-plugin-by-closure" }
allocator-api2 = "0.2"
bitvec = "1.0"

# Common dependencies
thiserror = "2.0"
