//!Generated from package "full_coverage2"
pub mod _puroro_root {
    pub use super::super::_puroro_root::*;
}
pub mod _puroro {
    pub use ::puroro::*;
}
pub struct Msg {
    i32_required: (),
    i32_optional: (),
    i32_repeated: (),
    float_required: (),
    float_optional: (),
    float_repeated: (),
    bytes_required: (),
    bytes_optional: (),
    bytes_repeated: (),
    string_required: (),
    string_optional: (),
    string_repeated: (),
    enum_required: (),
    enum_optional: (),
    enum_repeated: (),
    submsg_required: (),
    submsg_optional: (),
    submsg_repeated: (),
    i64_required: (),
    i64_optional: (),
    i64_repeated: (),
    u32_required: (),
    u32_optional: (),
    u32_repeated: (),
    u64_required: (),
    u64_optional: (),
    u64_repeated: (),
    s32_required: (),
    s32_optional: (),
    s32_repeated: (),
    s64_required: (),
    s64_optional: (),
    s64_repeated: (),
    fixed32_required: (),
    fixed32_optional: (),
    fixed32_repeated: (),
    fixed64_required: (),
    fixed64_optional: (),
    fixed64_repeated: (),
    sfixed32_required: (),
    sfixed32_optional: (),
    sfixed32_repeated: (),
    sfixed64_required: (),
    sfixed64_optional: (),
    sfixed64_repeated: (),
    f64_required: (),
    f64_optional: (),
    f64_repeated: (),
}
