//!Generated from package "full_coverage3"
pub mod _puroro_root {
    pub use super::super::_puroro_root::*;
}
pub mod _puroro {
    pub use ::puroro::*;
}
pub struct Msg {
    i32_unlabeled: (),
    i32_optional: (),
    i32_repeated: (),
    float_unlabeled: (),
    float_optional: (),
    float_repeated: (),
    bytes_unlabeled: (),
    bytes_optional: (),
    bytes_repeated: (),
    string_unlabeled: (),
    string_optional: (),
    string_repeated: (),
    enum_unlabeled: (),
    enum_optional: (),
    enum_repeated: (),
    submsg_unlabeled: (),
    submsg_optional: (),
    submsg_repeated: (),
    i64_unlabeled: (),
    i64_optional: (),
    i64_repeated: (),
    u32_unlabeled: (),
    u32_optional: (),
    u32_repeated: (),
    u64_unlabeled: (),
    u64_optional: (),
    u64_repeated: (),
    s32_unlabeled: (),
    s32_optional: (),
    s32_repeated: (),
    s64_unlabeled: (),
    s64_optional: (),
    s64_repeated: (),
    fixed32_unlabeled: (),
    fixed32_optional: (),
    fixed32_repeated: (),
    fixed64_unlabeled: (),
    fixed64_optional: (),
    fixed64_repeated: (),
    sfixed32_unlabeled: (),
    sfixed32_optional: (),
    sfixed32_repeated: (),
    sfixed64_unlabeled: (),
    sfixed64_optional: (),
    sfixed64_repeated: (),
    f64_unlabeled: (),
    f64_optional: (),
    f64_repeated: (),
}
