[package]
name = "puroro-codegen"
version = "0.15.0"
edition = "2021"

[dependencies]
culpa = "1.0.2"
ipc-channel = "0.19.0"
itertools = "0.14.0"
prettyplease = "0.2.27"
proc-macro2 = "1.0.92"
puroro = { path = "../puroro" }
quither = "0.5.0"
quote = "1.0.38"
syn = { version = "2.0.95", features = ["extra-traits"] }
thiserror = "2.0.9"

[lib]
