[package]
name = "puroro"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A Rust-idiomatic implementation of Google Protocol Buffers"
readme = "../README.md"

[dependencies]
protobuf-core.workspace = true
allocator-api2.workspace = true
bitvec.workspace = true
thiserror.workspace = true
allocator_extras.workspace = true
once-list2 = "0.4.0"
orx-split-vec.workspace = true
bytes = "1"
futures-io = "0.3"
futures = "0.3"

[features]
default = []
